llamaqa-en:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/llamaqa-en
    ref_col: answer
    query_col: query
    batch_size: 1

llamaqa-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/llamaqa-zh
    ref_col: answer
    query_col: query
    batch_size: 1

triviaqa-en:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/triviaqa-en
    ref_col: answer
    query_col: query
    batch_size: 1

triviaqa-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/triviaqa-zh
    ref_col: answer
    query_col: query
    batch_size: 1

webq-en:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/webq-en
    ref_col: answer
    query_col: query
    batch_size: 1

webq-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/webq-zh
    ref_col: answer
    query_col: query
    batch_size: 1

chinesesimpleqa-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/chinesesimpleqa-zh
    ref_col: answer
    query_col: query
    batch_size: 1

chinese_quiz-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/chinese_quiz-zh
    ref_col: answer
    query_col: query
    batch_size: 1

livelihood_policy-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/livelihood_policy-zh
    ref_col: answer
    query_col: query
    batch_size: 1