ceval-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/ceval-zh
    ref_col: answer
    query_col: query
    batch_size: 1

agieval-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/agieval-zh
    ref_col: answer
    query_col: query
    batch_size: 1