esd:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TeleSpeech-AudioBench/esd-zh
    ref_col: query_emo
    query_col: query
    extra_col: ["query_emo_zh", "ref_answer", "ref_answer_emo", "ref_answer_emo_zh"]
    batch_size: 1