human_acceptance-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/human_accept-zh
    ref_col: answer
    query_col: query
    batch_size: 1

human_chitchat-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/human_chitchat-zh
    ref_col: answer
    query_col: query
    batch_size: 1