empathy_response_lexical-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/empathy_response_lexical-zh
    ref_col: query_emo
    query_col: query
    extra_col: ["query_emo_zh", "answer", "answer_emo", "answer_emo_zh"]
    batch_size: 1

empathy_response_acoustic-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/empathy_response_acoustic-zh
    ref_col: query_emo
    query_col: query
    extra_col: ["query_emo_zh", "answer", "answer_emo", "answer_emo_zh"]
    batch_size: 1

para_mix300-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/para_mix300-zh
    query_col: query
    ref_col: answer
    extra_col: ["para_name"]

age-zh:
  class: src.dataset.BatchLoader
  args:
    file: Tele-AI/TELEVAL/age-zh
    query_col: query
    ref_col: age
    extra_col: ["answer_age", "answer_common"]